name: FrozedTeams
main: club.frozed.frozedteams.FrozedTeams
description: MineHQ MCTeams replica by Elb1to and Tincho.
version: 1.0
authors:
  - Elb1to
  - Tinchx
  - FrozedDevelopment
  - GMK Services